language: cpp

before_install:
  - wget http://dev-www.libreoffice.org/src/cppunit-1.13.2.tar.gz
  - tar -xvzf cppunit-1.13.2.tar.gz 
  - cd cppunit-1.13.2
  - mkdir -p home
  - ./configure --prefix=$HOME 
  - make
  - sudo make install
  - cd ..
  - export CPLUS_INCLUDE_PATH=$HOME/include:$CPLUS_INCLUDE_PATH
  - export LIBRARY_PATH=$HOME/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH


script:
  - make
  - make tests
