language: cpp

before_install:
  - wget http://dev-www.libreoffice.org/src/cppunit-1.13.2.tar.gz
  - tar -xvzf cppunit-1.13.2.tar.gz 
  - cd cppunit-1.13.2
  - mkdir cppunit-1.13.2/home/
  - ./configure --prefix=./cppunit-1.13.2/home/ --with-pthreads=no
  - make
  - make install
  - export CPLUS_INCLUDE_PATH=cppunit-1.13.2/home/include:$CPLUS_INCLUDE_PATH
  - export LIBRARY_PATH=cppunit-1.13.2/home/lib:$LIBRARY_PATH
  - export LD_LIBRARY_PATH=cppunit-1.13.2/home/lib:$LD_LIBRARY_PATH


script:
  - make
